### PR TITLE
Fix docstrings for controllers

### LINKED ISSUE #443: Fix API docstrings
Hello team,

It is necessary to complete an overall review and update/fix API documentation. Some of the bugs reported:

image

`agent_id_list` should be called `ids` and its type should be `String[]`

image

`agent_id` should be called `id`

image

We should improve and unify descriptions, `List of selected fields separated by commas`

Best regards,

David J. Iglesias

### PR DESCRIPTION
**Pull request by druizz90**
Hi team,

This PR closes #443. Some docstrings were fixed in order to generate the API documentation for `3.10` version.

`ids` parameters were fixed as we did in #441.

Best regards,

Demetrio.

### CODE REVIEW

**Comment by druizz90** [comment]
# Tests performed

## Mocha tests

### Active Response

```javascript
 mocha test/test_active_response.js 


  Active Response
    PUT/active-response/:agent_id
      ✓ Request (625ms)
      ✓ Command not found (331ms)
      ✓ Agent does not exist (322ms)
      ✓ Agent ID not valid


  4 passing (1s)

```

### Agents

```javascript
# mocha test/test_agents.js --timeout=10000


  Agents
    GET/agents
      ✓ Request (305ms)
      ✓ Pagination (324ms)
      ✓ Retrieve all elements with limit=0 (319ms)
      ✓ Sort (323ms)
      ✓ Wrong Sort (322ms)
      ✓ Search (342ms)
      ✓ Selector (355ms)
      ✓ Not allowed selector (341ms)
      ✓ Version (314ms)
      ✓ Os.platform (320ms)
      ✓ Os.version (307ms)
      ✓ ManagerHost (327ms)
      ✓ Filters: status (477ms)
      ✓ Filters: status 2 (326ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: older_than (312ms)
      ✓ Filters: group (322ms)
      ✓ Select: single field (307ms)
      ✓ Select: multiple fields (394ms)
      ✓ Select: wrong field (340ms)
      ✓ Select: invalid character
      ✓ Filters: query (339ms)
    GET/agents/summary
      ✓ Request (312ms)
    GET/agents/summary/os
      ✓ Request (442ms)
    GET/agents/outdated
      ✓ Request (502ms)
    GET/agents/:agent_id
      ✓ Request (manager) (338ms)
      ✓ Request (agent) (373ms)
      ✓ Selector (359ms)
      ✓ Not allowed selector (327ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (364ms)
      ✓ Select (384ms)
      ✓ Select: wrong field (449ms)
    GET/agents/name/:agent_name
      ✓ Request (573ms)
      ✓ Wrong name (394ms)
      ✓ Selector (470ms)
      ✓ Not allowed selector (504ms)
    GET/agents/:agent_id/key
      ✓ Request (479ms)
      ✓ Params: Bad agent id
      ✓ Errors: No key (452ms)
    PUT/agents/groups/:group_id
      ✓ Request (401ms)
      ✓ Params: Bad group name
      ✓ Params: Group already exists (347ms)
    PUT/agents/:agent_id/group/:group_id
      ✓ Request (503ms)
      ✓ Params: Bad agent name
      ✓ Params: Agent does not exist (562ms)
      ✓ Params: Replace parameter (317ms)
    POST/agents/groups/:group_id/files/:file_name
      ✓ Request (413ms)
      ✓ ErrorOnBadGroup (321ms)
      ✓ ErrorOnEmptyConf
      ✓ OnlyAgentConfAllowed (366ms)
      ✓ InvalidConfDetected
      ✓ WrongConfDetected (451ms)
      ✓ TooBigXML
    GET/agents/no_group
      ✓ Request (396ms)
      ✓ Pagination (360ms)
      ✓ Retrieve all elements with limit=0 (341ms)
      ✓ Sort (321ms)
      ✓ Search (316ms)
      ✓ Select (325ms)
      ✓ Wrong select (306ms)
      ✓ Filter: status (317ms)
    GET/agents/groups
      ✓ Request (312ms)
      ✓ Retrieve all elements with limit=0 (309ms)
      ✓ Hash algorithm (339ms)
      ✓ Wrong Hash algorithm (362ms)
    GET/agents/groups/:group_id
      ✓ Request (495ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (411ms)
      ✓ Select (536ms)
      ✓ Filter: status (348ms)
    GET/agents/groups/:group_id/configuration
      ✓ Request (483ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (339ms)
    GET/agents/groups/:group_id/files
      ✓ Request (315ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (312ms)
      ✓ Hash algorithm (330ms)
      ✓ Wrong Hash algorithm (348ms)
    GET/agents/groups/:group_id/files/:filename
      ✓ Request (320ms)
      ✓ UsingFormatAgentConfXML (357ms)
      ✓ UsingFormatAgentConfJSON (374ms)
      ✓ UsingFormatRootcheckXML (353ms)
      ✓ UsingFormatRootcheckJSON (350ms)
      ✓ Params: Bad group name
    POST/agents/groups/:group_id/configuration
      ✓ Request (311ms)
      ✓ ErrorOnBadGroup (312ms)
      ✓ ErrorOnEmptyConf
      ✓ InvalidConfDetected
      ✓ WrongConfDetected (335ms)
      ✓ TooBigXML
    DELETE/agents/:agent_id/group
      ✓ Request (372ms)
      ✓ Errors: ID is not present (316ms)
      ✓ Params: Bad agent id
    DELETE/agents/:agent_id/group/:group_id
      ✓ Request (363ms)
      ✓ Errors: ID is not present (379ms)
      ✓ Errors: Group is not present (365ms)
      ✓ Params: Bad agent id
      ✓ Params: Bad group id (338ms)
    DELETE/agents/groups/:group_id
      ✓ Request (349ms)
      ✓ Params: Bad group id
    DELETE/agents
      ✓ Request
      ✓ Filter: older_than, status and ids (3904ms)
      ✓ Errors: Get deleted agent (372ms)
      ✓ Filter: older_than (315ms)
    GET/agents/stats/distinct
      ✓ Request (337ms)
      ✓ Pagination (347ms)
      ✓ Retrieve all elements with limit=0 (327ms)
      ✓ Sort (329ms)
      ✓ Search (376ms)
      ✓ Select (331ms)
      ✓ Wrong select (329ms)
    GET/agents/:agent/config/:component/:configuration
      ✓ Request-Agent-Client (406ms)
      ✓ Request-Agent-Buffer (377ms)
      ✓ Request-Agent-Labels (328ms)
      ✓ Request-Agent-Internal (365ms)
      ✓ Request-Agentless-Agentless (369ms)
      ✓ Request-Analysis-Global (327ms)
      ✓ Request-Analysis-Active-response (363ms)
      ✓ Request-Analysis-Alerts (386ms)
      ✓ Request-Analysis-Command (338ms)
      ✓ Request-Analysis-Internal (380ms)
      ✓ Request-Auth-Auth (374ms)
      ✓ Request-Com-Active-response (388ms)
      ✓ Request-Com-Internal (411ms)
      ✓ Request-Csyslog-Csyslog (378ms)
      ✓ Request-Integrator-Integration (382ms)
      ✓ Request-Logcollector-Localfile (363ms)
      ✓ Request-Logcollector-Socket (345ms)
      ✓ Request-Logcollector-Internal (362ms)
      ✓ Request-Mail-Global (344ms)
      ✓ Request-Mail-Alerts (341ms)
      ✓ Request-Mail-Internal (318ms)
      ✓ Request-Monitor-Internal (344ms)
      ✓ Request-Request-Remote (337ms)
      ✓ Request-Request-Internal (361ms)
      ✓ Request-Syscheck-Syscheck (345ms)
      ✓ Request-Syscheck-Rootcheck (368ms)
      ✓ Request-Syscheck-Internal (356ms)
      ✓ Request-Wmodules-Wmodules (379ms)
    PUT/agents/restart
      ✓ Request (427ms)
    PUT/agents/:agent_id/restart
      ✓ Request (390ms)
      ✓ Params: Bad agent id
      ✓ Request (407ms)
    POST/agents/restart
      ✓ Request (379ms)
      ✓ Params: A good id and a bad one (417ms)
      ✓ Params: Bad agent id
      ✓ Request (453ms)


  149 passing (54s)

```

### Agents 2

```javascript
# mocha test/test_agents_2.js                


  Agents
    PUT/agents/:agent_name
      ✓ Request (516ms)
      ✓ Errors: Name already present (358ms)
      ✓ Params: Bad agent name
    DELETE/agents/:agent_id
      ✓ Request (339ms)
      ✓ Errors: ID is not present (422ms)
      ✓ Params: Bad agent id
    POST/agents
      Any
        ✓ Request (380ms)
        ✓ Check key (340ms)
        ✓ Errors: Name already present (598ms)
        ✓ Filters: Missing field name
        ✓ Filters: Invalid field
      IP Automatic
        ✓ Request: Automatic IP (441ms)
        ✓ Errors: Duplicated IP (393ms)
      IP
        ✓ Request (406ms)
        ✓ Filters: Bad IP
        ✓ Filters: Bad IP 2
    POST/agents/insert
      Any
        ✓ Request (378ms)
        1) Insert agent with force parameter (ID and name already presents)
        ✓ Errors: Name already present (320ms)
        2) Errors: ID already present
        ✓ Errors: Invalid key (363ms)
        ✓ Filters: Missing fields
        ✓ Filters: Invalid field
      IP Automatic
        ✓ Request: Automatic IP (362ms)
        ✓ Errors: Duplicated IP (343ms)
      IP
        ✓ Request (385ms)
        ✓ Filters: Bad IP
        ✓ Filters: Bad IP 2


  26 passing (11s)
  2 failing

  1) Agents
       POST/agents/insert
         Any
           Insert agent with force parameter (ID and name already presents):
     Uncaught AssertionError: expected Object { error: 9012, message: 'Duplicated ID' } to have property data
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value [as properties] (node_modules/should/cjs/should.js:335:19)
      at Test.<anonymous> (test/test_agents_2.js:485:42)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at /wazuh-api/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:619:12)
      at /wazuh-api/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  2) Agents
       POST/agents/insert
         Any
           Errors: ID already present:
     Uncaught AssertionError: expected Object {
  error: 0,
  data: Object {
    id: '750',
    key: 'NzUwIE5ld0FnZW50UG9zdEluc2VydCBhbnkgMWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnaGk2NA=='
  }
} to have property message
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value [as properties] (node_modules/should/cjs/should.js:335:19)
      at Test.<anonymous> (test/test_agents_2.js:526:42)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at /wazuh-api/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:619:12)
      at /wazuh-api/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

```

# App

```javascript
# mocha test/test_app.js      


  App
    Authentication
      ✓ Wrong USER
      ✓ Wrong password
      ✓ Home
    Requests
      ✓ Inexistent request
      ✓ API version


  5 passing (81ms)
```

### Cluster

```javascript
# mocha test/test_cluster.js 


  Cluster
    GET/cluster/nodes
      ✓ Request (483ms)
      ✓ Pagination (328ms)
      ✓ Retrieve all elements with limit=0 (330ms)
      ✓ Sort (333ms)
      ✓ Search (329ms)
      ✓ Filters: type (323ms)
      ✓ Filters: invalid type (330ms)
      ✓ Select (334ms)
      ✓ Select 2 (329ms)
      ✓ Wrong select (323ms)
    GET/cluster/:node_id/stats
      ✓ Cluster stats (302ms)
      ✓ Unexisting node stats (339ms)
      ✓ Analysisd stats (351ms)
      ✓ Remoted stats (333ms)
    GET/cluster/nodes/:node_name
      ✓ Request (302ms)
      ✓ Request wrong name (336ms)
    GET/cluster/status
      ✓ Request (320ms)
    GET/cluster/config
      ✓ Request (322ms)
    GET/cluster/healthcheck
      ✓ Request (333ms)
      ✓ Filter: node name (372ms)
    POST/cluster/:node_id/files
      ✓ Upload ossec.conf (master) (352ms)
      ✓ Upload ossec.conf (worker) (371ms)
      ✓ Upload new rules (342ms)
      ✓ Upload rules (overwrite=true) (334ms)
      ✓ Upload rules (overwrite=false) (353ms)
      ✓ Upload new decoder (338ms)
      ✓ Upload decoder (overwrite=true) (340ms)
      ✓ Upload decoder (without overwrite parameter) (326ms)
      ✓ Upload new list (385ms)
      ✓ Upload list (overwrite=true) (336ms)
      ✓ Upload list (overwrite=false) (381ms)
      ✓ Upload corrupted ossec.conf (master)
      ✓ Upload corrupted ossec.conf (worker)
      ✓ Upload malformed rules
      ✓ Upload rules to unexisting node (395ms)
      ✓ Upload malformed decoder
      ✓ Upload decoder to unexisting node (407ms)
      ✓ Upload malformed list
      ✓ Upload list to unexisting node (438ms)
      ✓ Upload list with empty path
      ✓ Upload a file with a wrong content type
    GET/cluster/:node_id/files
      ✓ Request ossec.conf (master) (695ms)
      ✓ Request ossec.conf (worker) (569ms)
      ✓ Request rules (local) (501ms)
      ✓ Request rules (global) (509ms)
      ✓ Request decoders (local) (552ms)
      ✓ Request decoders (global) (442ms)
      ✓ Request lists (440ms)
      ✓ Request wrong path 1
      ✓ Request wrong path 2
      ✓ Request wrong path 3
      ✓ Request unexisting file (363ms)
      ✓ Request file from unexisting node (426ms)
      ✓ Request file with empty path
      ✓ Request file with validation parameter (true) (646ms)
    GET/cluster/:node_id/configuration/validation (manager and worker OK)
      ✓ Request validation (master) (1268ms)
      ✓ Request validation (worker) (1194ms)
      ✓ Request validation (all nodes) (1360ms)
    GET/cluster/:node_id/configuration/validation (manager KO, worker OK)
      ✓ Request validation (master) (398ms)
      ✓ Request validation (worker) (1330ms)
      ✓ Request validation (all nodes) (1325ms)
    GET/cluster/:node_id/configuration/validation (manager OK, worker KO)
      ✓ Request validation (master) (1009ms)
      ✓ Request validation (worker) (521ms)
      ✓ Request validation (all nodes) (1575ms)
    GET/cluster/:node_id/configuration/validation (manager and worker KO)
      ✓ Request validation (master) (318ms)
      ✓ Request validation (worker) (424ms)
      ✓ Request validation (all nodes) (454ms)
    DELETE/cluster/:node_id/files
      ✓ Delete rules (master) (607ms)
      ✓ Delete decoders (master) (814ms)
      ✓ Delete CDB list (master) (496ms)
      ✓ Delete file with empty path
    GET/cluster/master/config/:component/:configuration
      ✓ Request-Agentless-Agentless (501ms)
      ✓ Request-Analysis-Global (466ms)
      ✓ Request-Analysis-Active-response (397ms)
      ✓ Request-Analysis-Alerts (458ms)
      ✓ Request-Analysis-Command (537ms)
      ✓ Request-Analysis-Internal (552ms)
      ✓ Request-Auth-Auth (454ms)
      ✓ Request-Com-Active-response (455ms)
      ✓ Request-Com-Internal (372ms)
      ✓ Request-Csyslog-Csyslog (441ms)
      ✓ Request-Integrator-Integration (532ms)
      ✓ Request-Logcollector-Localfile (404ms)
      ✓ Request-Logcollector-Socket (366ms)
      ✓ Request-Logcollector-Internal (565ms)
      ✓ Request-Mail-Global (359ms)
      ✓ Request-Mail-Alerts (342ms)
      ✓ Request-Mail-Internal (358ms)
      ✓ Request-Monitor-Internal (376ms)
      ✓ Request-Request-Remote (372ms)
      ✓ Request-Request-Internal (581ms)
      ✓ Request-Syscheck-Syscheck (464ms)
      ✓ Request-Syscheck-Rootcheck (353ms)
      ✓ Request-Syscheck-Internal (357ms)
      ✓ Request-Wmodules-Wmodules (365ms)
    PUT/cluster/:node_id/restart
      ✓ Request (worker) (364ms)
      ✓ Request (master) (368ms)


  97 passing (46s)

```

### Decoders

```javascript
# mocha test/test_decoders.js 


  Decoders
    GET/decoders
      ✓ Request (692ms)
      ✓ Pagination (384ms)
      ✓ Retrieve all elements with limit=0 (372ms)
      ✓ Sort (367ms)
      ✓ Search (362ms)
      ✓ Filters: File (364ms)
      ✓ Filters: Path (359ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
    GET/decoders/files
      ✓ Request (323ms)
      ✓ Pagination (325ms)
      ✓ Retrieve all elements with limit=0 (316ms)
      ✓ Sort (331ms)
      ✓ Search (318ms)
    GET/decoders/parents
      ✓ Request (364ms)
      ✓ Pagination (353ms)
      ✓ Retrieve all elements with limit=0 (377ms)
      ✓ Sort (362ms)
      ✓ Search (369ms)
    GET/decoders/:decoder_name
      ✓ Request (363ms)
      ✓ Pagination (360ms)
      ✓ Retrieve all elements with limit=0 (364ms)
      ✓ Sort (373ms)
      ✓ Search (367ms)


  24 passing (8s)

```

### List

```javascript
# mocha test/test_lists.js    


  Lists
    GET/lists
      ✓ Request (623ms)
      ✓ Pagination (333ms)
      ✓ Retrieve all elements with limit=0 (317ms)
      ✓ Sort (332ms)
      ✓ Search (317ms)
      ✓ Filters: Path (328ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
    GET/lists/files
      ✓ Request (333ms)
      ✓ Pagination (306ms)
      ✓ Retrieve all elements with limit=0 (344ms)
      ✓ Sort (323ms)
      ✓ Search (347ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field


  15 passing (4s)

```

### Manager

```javascript
# mocha test/test_manager.js 


  Manager
    GET/manager/status
      ✓ Request (392ms)
    GET/manager/info
      ✓ Request (390ms)
    GET/manager/configuration
      ✓ Request (379ms)
      ✓ Filters: Missing field section
      ✓ Filters: Section (432ms)
      ✓ Errors: Invalid Section (439ms)
      ✓ Filters: Section - field (389ms)
      ✓ Errors: Invalid field (361ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field (38ms)
    GET/manager/stats
      ✓ Request (378ms)
      ✓ Filters: date (397ms)
      ✓ Filters: Invalid date
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
    GET/manager/stats/hourly
      ✓ Request (328ms)
    GET/manager/stats/weekly
      ✓ Request (337ms)
    GET/manager/stats/analysisd
      ✓ Request (332ms)
    GET/manager/stats/remoted
      ✓ Request (381ms)
    GET/manager/logs
      ✓ Request (382ms)
      ✓ Pagination (359ms)
      ✓ Retrieve all elements with limit=0 (382ms)
      ✓ Sort (370ms)
      ✓ SortField (522ms)
      ✓ Search (591ms)
      ✓ Filters: type_log (621ms)
      ✓ Filters: category (480ms)
      ✓ Filters: type_log and category (444ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
    GET/manager/logs/summary
      ✓ Request (478ms)
    POST/manager/files
      ✓ Upload ossec.conf (341ms)
      ✓ Upload ossec.conf (overwrite=false) (342ms)
      ✓ Upload rules (new rule) (337ms)
      ✓ Upload rules (overwrite=true) (325ms)
      ✓ Upload rules (overwrite=false) (332ms)
      ✓ Upload decoder (overwrite=true) (328ms)
      ✓ Upload decoder (without overwrite parameter) (340ms)
      ✓ Upload list (overwrite=true) (323ms)
      ✓ Upload list (without overwrite parameter) (468ms)
      ✓ Upload malformed rule
      ✓ Upload malformed decoder
      ✓ Upload malformed list
      ✓ Upload list with empty path
      ✓ Upload a file with a wrong content type
    GET/manager/files
      ✓ Request ossec.conf (317ms)
      ✓ Request rules (local) (318ms)
      ✓ Request rules (global) (339ms)
      ✓ Request decoders (local) (327ms)
      ✓ Request decoders (global) (340ms)
      ✓ Request lists (312ms)
      ✓ Request wrong path 1
      ✓ Request wrong path 2
      ✓ Request wrong path 3
      ✓ Request unexisting file (327ms)
      ✓ Request file with empty path
      ✓ Request file with validation parameter (true) (426ms)
    DELETE/manager/files
      ✓ Delete rules (350ms)
      ✓ Delete decoders (349ms)
      ✓ Delete CDB list (337ms)
      ✓ Delete file with empty path
    GET/manager/configuration/validation (OK)
      ✓ Request validation  (1208ms)
    GET/manager/configuration/validation (KO)
      ✓ Request validation (325ms)
    GET/manager/config/:component/:configuration
      ✓ Request-Agentless-Agentless (346ms)
      ✓ Request-Analysis-Global (321ms)
      ✓ Request-Analysis-Active-response (317ms)
      ✓ Request-Analysis-Alerts (324ms)
      ✓ Request-Analysis-Command (324ms)
      ✓ Request-Analysis-Internal (321ms)
      ✓ Request-Auth-Auth (338ms)
      ✓ Request-Com-Active-response (328ms)
      ✓ Request-Com-Internal (327ms)
      ✓ Request-Csyslog-Csyslog (315ms)
      ✓ Request-Integrator-Integration (329ms)
      ✓ Request-Logcollector-Localfile (324ms)
      ✓ Request-Logcollector-Socket (319ms)
      ✓ Request-Logcollector-Internal (352ms)
      ✓ Request-Mail-Global (345ms)
      ✓ Request-Mail-Alerts (327ms)
      ✓ Request-Mail-Internal (336ms)
      ✓ Request-Monitor-Internal (359ms)
      ✓ Request-Request-Remote (332ms)
      ✓ Request-Request-Internal (334ms)
      ✓ Request-Syscheck-Syscheck (317ms)
      ✓ Request-Syscheck-Rootcheck (328ms)
      ✓ Request-Syscheck-Internal (343ms)
      ✓ Request-Wmodules-Wmodules (332ms)
    PUT/manager/restart
      ✓ Request (330ms)


  88 passing (28s)

```

### Rootcheck

```javascript
# mocha test/test_rootcheck.js 


  Rootcheck
    GET/rootcheck/:agent_id/last_scan
      ✓ Request (383ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (390ms)
    DELETE/rootcheck/:agent_id
      ✓ Request (544ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (503ms)
    DELETE/rootcheck
      ✓ Request (1812ms)
    PUT/rootcheck/:agent_id
      ✓ Request (786ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (363ms)
    PUT/rootcheck
      ✓ Request (389ms)


  11 passing (5s)

```

### Rules

```javascript
# mocha test/test_rules.js     


  Rules
    GET/rules
      ✓ Request (617ms)
      ✓ Pagination (607ms)
      ✓ Retrieve all elements with limit=0 (585ms)
      ✓ Sort (630ms)
      ✓ Search (659ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: status (614ms)
      ✓ Filters: group (637ms)
      ✓ Filters: level (1) (562ms)
      ✓ Filters: level (2) (704ms)
      ✓ Filters: path (560ms)
      ✓ Filters: file (518ms)
      ✓ Filters: pci (685ms)
      ✓ Filters: gdpr (573ms)
      ✓ Filters: hipaa (1195ms)
      ✓ Filters: nist-800-53 (1040ms)
      ✓ Filters: gpg13 (595ms)
    GET/rules/groups
      ✓ Request (563ms)
      ✓ Pagination (543ms)
      ✓ Retrieve all elements with limit=0 (514ms)
      ✓ Sort (503ms)
      ✓ Search (507ms)
      ✓ Filters: Invalid filter
    GET/rules/pci
      ✓ Request (515ms)
      ✓ Pagination (496ms)
      ✓ Retrieve all elements with limit=0 (513ms)
      ✓ Sort (497ms)
      ✓ Search (532ms)
      ✓ Filters: Invalid filter
    GET/rules/gdpr
      ✓ Request (518ms)
      ✓ Pagination (532ms)
      ✓ Retrieve all elements with limit=0 (508ms)
      ✓ Sort (498ms)
      ✓ Search (488ms)
      ✓ Filters: Invalid filter
    GET/rules/gpg13
      ✓ Request (492ms)
      ✓ Pagination (500ms)
      ✓ Retrieve all elements with limit=0 (491ms)
      ✓ Sort (586ms)
      ✓ Search (494ms)
      ✓ Filters: Invalid filter
    GET/rules/hipaa
      ✓ Request (486ms)
      ✓ Pagination (482ms)
      ✓ Retrieve all elements with limit=0 (489ms)
      ✓ Sort (519ms)
      ✓ Search (499ms)
      ✓ Filters: Invalid filter
    GET/rules/nist-800-53
      ✓ Request (528ms)
      ✓ Pagination (500ms)
      ✓ Retrieve all elements with limit=0 (494ms)
      ✓ Sort (503ms)
      ✓ Search (500ms)
      ✓ Filters: Invalid filter
    GET/rules/files
      ✓ Request (328ms)
      ✓ Pagination (330ms)
      ✓ Retrieve all elements with limit=0 (332ms)
      ✓ Sort (413ms)
      ✓ Search (397ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: status (338ms)
      ✓ Filters: download (333ms)
    GET/rules/:rule_id
      ✓ Request (473ms)
      ✓ Pagination (490ms)
      ✓ Retrieve all elements with limit=0 (523ms)
      ✓ Sort (571ms)
      ✓ Search (524ms)
      ✓ Filters: Invalid filter
      ✓ Params: Bad rule id
      ✓ Params: No rule (483ms)


  71 passing (32s)

```

### SCA

```javascript
# mocha test/test_sca.js   


  SecurityConfigurationAssessment
    GET/sca/:agent_id
      ✓ Request (374ms)
      ✓ Pagination (338ms)
      ✓ Retrieve all elements with limit=0 (333ms)
      ✓ Sort (363ms)
      ✓ Search (340ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (316ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: query (332ms)
      ✓ Retrieve all elements with limit=0 (330ms)
    GET/sca/:agent_id/checks/:policy_id
      ✓ Request (339ms)
      ✓ Pagination (382ms)
      ✓ Retrieve all elements with limit=0 (359ms)
      ✓ Sort (359ms)
      ✓ Search (377ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (323ms)
      ✓ Check not found (389ms)
      ✓ Retrieve all elements with limit=0 (380ms)


  20 passing (6s)

```

### Summary

```javascript
# mocha test/test_summary.js 


  Summary
    GET/summary/agents
      ✓ Request (390ms)


  1 passing (397ms)

```

### Syscheck

```javascript
# mocha test/test_syscheck.js 


  Syscheck
    GET/syscheck/:agent_id
      ✓ Request (406ms)
      ✓ Pagination (342ms)
      ✓ Retrieve all elements with limit=0 (356ms)
      ✓ Sort (345ms)
      ✓ Search (565ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (312ms)
      ✓ Filters: Invalid filter (54ms)
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: file (336ms)
      ✓ Filters: type (327ms)
      ✓ Filters: summary (331ms)
      ✓ Filters: md5 (343ms)
      ✓ Filters: sha1 (338ms)
      ✓ Filters: sha256 (347ms)
      ✓ Filters: hash (349ms)
    GET/syscheck/:agent_id/last_scan
      ✓ Request (329ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (308ms)
    DELETE/syscheck/:agent_id
      ✓ Request (329ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (321ms)
    DELETE/experimental/syscheck
      ✓ Request (863ms)
    PUT/syscheck/:agent_id
      ✓ Request (324ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (316ms)
    PUT/syscheck
      ✓ Request (358ms)


  27 passing (8s)

```

### Syscollector

```javascript
# mocha test/test_syscollector.js 


  Syscollector
    GET/syscollector/:agent_id/os
      ✓ Request (400ms)
      ✓ Selector (381ms)
      ✓ Not allowed selector (404ms)
    GET/syscollector/:agent_id/hardware
      ✓ Request (345ms)
      ✓ Selector (404ms)
      ✓ Not allowed selector (481ms)
    GET/syscollector/:agent_id/packages
      ✓ Request (383ms)
      ✓ Selector (432ms)
      ✓ Not allowed selector (362ms)
      ✓ Pagination (352ms)
      ✓ Wrong limit
      ✓ Sort - (337ms)
      ✓ Sort + (328ms)
      ✓ Wrong Sort (320ms)
      ✓ Search (358ms)
      ✓ Filter: vendor (352ms)
      ✓ Filter: name (356ms)
      ✓ Filter: architecture (363ms)
      ✓ Filter: format (677ms)
      ✓ Wrong filter
    GET/experimental/syscollector/packages
      ✓ Request (495ms)
      ✓ Selector (552ms)
      ✓ Not allowed selector (367ms)
      ✓ Pagination (607ms)
      ✓ Wrong limit
      ✓ Sort - (399ms)
      ✓ Sort + (368ms)
      ✓ Wrong Sort (354ms)
      ✓ Search (513ms)
      ✓ Filter: vendor (772ms)
      ✓ Filter: name (415ms)
      ✓ Filter: architecture (412ms)
      ✓ Filter: format (507ms)
      ✓ Wrong filter
    GET/experimental/syscollector/os
      ✓ Request (356ms)
      ✓ Selector (387ms)
      ✓ Not allowed selector (461ms)
      ✓ Pagination (393ms)
      ✓ Wrong limit
      ✓ Search (404ms)
      ✓ Wrong filter
      ✓ Filter: architecture (385ms)
      ✓ Filter: os_name (382ms)
      ✓ Filter: release (395ms)
    GET/experimental/syscollector/hardware
      ✓ Request (399ms)
      ✓ Selector (396ms)
      ✓ Not allowed selector (396ms)
      ✓ Pagination (395ms)
      ✓ Wrong limit
      ✓ Search (383ms)
      ✓ Wrong filter
      ✓ Wrong Sort (361ms)
      ✓ Filter: ram_total (591ms)
      ✓ Filter: cpu_cores (446ms)
      ✓ Filter: cpu_mhz (705ms)
      ✓ Filter: board_serial (645ms)
    GET/experimental/syscollector/processes
      ✓ Request (527ms)
      ✓ Selector (702ms)
      ✓ Not allowed selector (563ms)
      ✓ Pagination (409ms)
      ✓ Wrong limit
      ✓ Search (407ms)
      ✓ Wrong filter
      ✓ Wrong Sort (367ms)
      ✓ Filter: state (383ms)
      ✓ Filter: ppid (401ms)
      ✓ Filter: egroup (401ms)
      ✓ Filter: euser (368ms)
      ✓ Filter: fgroup (388ms)
      ✓ Filter: name (412ms)
      ✓ Filter: nlwp (389ms)
      ✓ Filter: pgrp (439ms)
      ✓ Filter: priority (373ms)
      ✓ Filter: rgroup (387ms)
      ✓ Filter: ruser (393ms)
      ✓ Filter: sgroup (393ms)
      ✓ Filter: suser (381ms)
    GET/experimental/syscollector/ports
      ✓ Request (378ms)
      ✓ Selector (407ms)
      ✓ Not allowed selector (387ms)
      ✓ Pagination (396ms)
      ✓ Wrong limit
      ✓ Search (412ms)
      ✓ Wrong filter
      ✓ Wrong Sort (395ms)
      ✓ Filter: protocol (402ms)
      ✓ Filter: local_ip (662ms)
      ✓ Filter: local_port (443ms)
      ✓ Filter: remote_ip (645ms)
      ✓ Filter: tx_queue (533ms)
      ✓ Filter: state (476ms)
    GET/syscollector/netaddr
      ✓ Request (642ms)
      ✓ Selector (514ms)
      ✓ Not allowed selector (559ms)
      ✓ Pagination (538ms)
      ✓ Wrong limit
      ✓ Search (735ms)
      ✓ Wrong filter
      ✓ Wrong Sort (541ms)
      ✓ Filter: iface (475ms)
      ✓ Filter: proto (495ms)
      ✓ Filter: address (466ms)
      ✓ Filter: broadcast (520ms)
      ✓ Filter: netmask (423ms)
    GET/experimental/syscollector/netproto
      ✓ Request (344ms)
      ✓ Selector (428ms)
      ✓ Not allowed selector (406ms)
      ✓ Pagination (392ms)
      ✓ Wrong limit
      ✓ Search (449ms)
      ✓ Wrong filter
      ✓ Wrong Sort (496ms)
      ✓ Filter: iface (471ms)
      ✓ Filter: type (386ms)
      ✓ Filter: gateway (406ms)
      ✓ Filter: dhcp (412ms)
    GET/experimental/syscollector/netiface
      ✓ Request (394ms)
      ✓ Selector (392ms)
      ✓ Not allowed selector (389ms)
      ✓ Pagination (391ms)
      ✓ Wrong limit
      ✓ Search (408ms)
      ✓ Wrong filter
      ✓ Wrong Sort (383ms)
      ✓ Filter: name (389ms)
      ✓ Filter: type (403ms)
      ✓ Filter: state (399ms)
      ✓ Filter: mtu (419ms)
      ✓ Filter: tx_packets (450ms)
      ✓ Filter: rx_packets (415ms)
      ✓ Filter: tx_bytes (415ms)
      ✓ Filter: rx_bytes (402ms)
      ✓ Filter: tx_errors (417ms)
      ✓ Filter: rx_errors (407ms)
      ✓ Filter: tx_dropped (431ms)
      ✓ Filter: rx_dropped (391ms)
    GET/syscollector/000/processes
      ✓ Request (334ms)
      ✓ Selector (342ms)
      ✓ Not allowed selector (383ms)
      ✓ Pagination (382ms)
      ✓ Wrong limit
      ✓ Search (368ms)
      ✓ Wrong filter
      ✓ Wrong Sort (402ms)
      ✓ Filter: state (337ms)
      ✓ Filter: ppid (375ms)
      ✓ Filter: egroup (353ms)
      ✓ Filter: euser (341ms)
      ✓ Filter: fgroup (348ms)
      ✓ Filter: name (359ms)
      ✓ Filter: nlwp (372ms)
      ✓ Filter: pgrp (342ms)
      ✓ Filter: priority (355ms)
      ✓ Filter: rgroup (364ms)
      ✓ Filter: ruser (334ms)
      ✓ Filter: sgroup (347ms)
      ✓ Filter: suser (359ms)
    GET/syscollector/000/ports
      ✓ Request (324ms)
      ✓ Selector (359ms)
      ✓ Not allowed selector (407ms)
      ✓ Pagination (522ms)
      ✓ Wrong limit
      ✓ Search (451ms)
      ✓ Wrong filter
      ✓ Wrong Sort (465ms)
      ✓ Filter: protocol (430ms)
      ✓ Filter: local_ip (381ms)
      ✓ Filter: local_port (372ms)
      ✓ Filter: remote_ip (351ms)
      ✓ Filter: tx_queue (320ms)
      ✓ Filter: state (328ms)
    GET/syscollector/000/netaddr
      ✓ Request (598ms)
      ✓ Selector (368ms)
      ✓ Not allowed selector (332ms)
      ✓ Pagination (351ms)
      ✓ Wrong limit
      ✓ Search (327ms)
      ✓ Wrong filter
      ✓ Wrong Sort (327ms)
      ✓ Filter: iface (325ms)
      ✓ Filter: proto (344ms)
      ✓ Filter: address (328ms)
      ✓ Filter: broadcast (325ms)
      ✓ Filter: netmask (340ms)
    GET/syscollector/000/netproto
      ✓ Request (313ms)
      ✓ Selector (323ms)
      ✓ Not allowed selector (328ms)
      ✓ Pagination (320ms)
      ✓ Wrong limit
      ✓ Search (333ms)
      ✓ Wrong filter
      ✓ Wrong Sort (318ms)
      ✓ Filter: iface (333ms)
      ✓ Filter: type (329ms)
      ✓ Filter: gateway (323ms)
      ✓ Filter: dhcp (332ms)
    GET/syscollector/000/netiface
      ✓ Request (324ms)
      ✓ Selector (322ms)
      ✓ Not allowed selector (347ms)
      ✓ Pagination (321ms)
      ✓ Wrong limit
      ✓ Search (336ms)
      ✓ Wrong filter
      ✓ Wrong Sort (317ms)
      ✓ Filter: name (329ms)
      ✓ Filter: type (330ms)
      ✓ Filter: state (346ms)
      ✓ Filter: mtu (333ms)
      ✓ Filter: tx_packets (376ms)
      ✓ Filter: rx_packets (353ms)
      ✓ Filter: tx_bytes (326ms)
      ✓ Filter: rx_bytes (333ms)
      ✓ Filter: tx_errors (324ms)
      ✓ Filter: rx_errors (340ms)
      ✓ Filter: tx_dropped (334ms)
      ✓ Filter: rx_dropped (350ms)


  216 passing (1m)

```

File: controllers/cluster.js [hunk 1]
```diff
@@ -537,7 +537,7 @@ router.get('/:node_id/files', cache(), function(req, res) {
  *
  * @apiParam {String} file Input file.
  * @apiParam {String} path Relative path were input file will be placed. This parameter is mandatory.
- * @apiParam {String} overwrite false to fail if file already exists (default). true to replace the existing file
+ * @apiParam {Bolean} overwrite Replaces the existing file. False by default.
```
Comment (davidjiglesias) [inline controllers/cluster.js]:
```suggestion
 * @apiParam {Boolean} overwrite Replaces the existing file. False by default.
```

File: controllers/decoders.js [hunk 2]
```diff
@@ -134,7 +134,7 @@ router.get('/parents', cache(), function(req, res) {
     req.apicacheGroup = "decoders";
 
     var data_request = {'function': '/decoders', 'arguments': {}};
-    var filters = {'offset': 'numbers', 'limit': 'numbers', 'sort':'sort_param', 'search':'search_param'};
+    var filters = {'offset': 'numbers', 'limit': 'numbers', 'sort':'sort_param', 'search': 'search_param'};
```
Comment (davidjiglesias) [inline controllers/decoders.js]:
```suggestion
    var filters = {'offset': 'numbers', 'limit': 'numbers', 'sort': 'sort_param', 'search': 'search_param'};
```

File: controllers/manager.js [hunk 3]
```diff
@@ -316,7 +316,7 @@ router.get('/stats/remoted', cache(), function(req, res) {
  * @apiGroup Files
  *
  * @apiParam {String} path Relative path of file. This parameter is mandatory.
- * @apiParam {String} validation Default false. true for validating the content of the file. An error will be returned file content is not strictly correct.
+ * @apiParam {String} validation Validates the content of the file. An error will be returned if file content is not strictly correct. False by default.
```
Comment (davidjiglesias) [inline controllers/manager.js]: Boolean?

File: controllers/manager.js [hunk 4]
```diff
@@ -391,7 +391,7 @@ router.delete('/files', cache(), function(req, res) {
  *
  * @apiParam {String} file Input file.
  * @apiParam {String} path Relative path were input file will be placed. This parameter is mandatory.
- * @apiParam {String} overwrite false to fail if file already exists (default). true to replace the existing file
+ * @apiParam {String} overwrite Replaces the existing file. False by default.
```
Comment (davidjiglesias) [inline controllers/manager.js]: Boolean?
